version: '3.6'

services:
  pdb:
    image: postgres:14.5-alpine
    restart: always
    container_name: postgres-db
    environment:
      - POSTGRES_DB=users
      - POSTGRES_USER=appUser
      - POSTGRES_PASSWORD=Postgres123
    ports:
      - '6543:5432'
    volumes:
      - ./db-data:/var/lib/postgresql/data
#  app:
#    image: 'users:0.0.1'
#    build:
#      context: .
#    container_name: users
#    depends_on:
#      - pdb
#    ports:
#      - 8989:8989
#    environment:
#      - RU_RINAT_USERS_DATABASE_URL=jdbc:postgresql://postgres-db:5432/users
#      - SPRING_DATASOURCE_USERNAME=app_user
#      - SPRING_DATASOURCE_PASSWORD=Postgres123
#      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
networks:
  my-network: